name: dynssh
description: A small server utility to dynamically update the SSH configuration for a remote host with dynamic IPs.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

executables:
  dynssh:

dependencies:
  args: ^2.4.0
  build_cli_annotations: ^2.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  meta: ^1.9.1
  riverpod: ^2.3.2

dev_dependencies:
  build_cli: ^2.2.1
  build_runner: ^2.3.3
  dart_pre_commit: ^4.1.0
  dart_test_tools: ^4.8.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  test: ^1.24.0

dart_pre_commit:
  flutter-compat: false
