name: dynssh
description: A small server utility to dynamically update the SSH configuration for a remote host with dynamic IPs.
version: 1.0.4
publish_to: none

environment:
  sdk: ^3.0.0

platforms:
  linux:
  macos:

executables:
  dynssh:

dependencies:
  args: ^2.4.2
  build_cli_annotations: ^2.1.0
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.9.1
  posix: ^5.0.0
  riverpod: ^2.3.7
  synchronized: ^3.1.0

dev_dependencies:
  build_cli: ^2.2.2
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  dart_pre_commit: ^5.2.1
  dart_test_tools: ^5.3.0
  freezed: ^2.4.2
  http: ^1.1.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.24.6

dart_pre_commit:
  flutter-compat: false

cider:
  link_template:
    tag: https://github.com/Skycoder42/dynssh/releases/tag/v%tag%
    diff: https://github.com/Skycoder42/dynssh/compare/v%from%...v%to%
