name: dynssh
description: A small server utility to dynamically update the SSH configuration for a remote host with dynamic IPs.
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.19.0 <3.0.0"

executables:
  dynssh:

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  dart_pre_commit: ^4.1.0
  dart_test_tools: ^4.8.0
  test: ^1.24.0

dart_pre_commit:
  flutter-compat: false
