name: dynssh
description: A small server utility to dynamically update the SSH configuration for a remote host with dynamic IPs.
version: 0.1.0
publish_to: none

environment:
  sdk: ^3.0.0

platforms:
  linux:
  macos:

executables:
  dynssh:

dependencies:
  args: ^2.4.1
  build_cli_annotations: ^2.1.0
  collection: ^1.17.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  logging: ^1.1.1
  meta: ^1.9.1
  posix: ^5.0.0
  riverpod: ^2.3.6

dev_dependencies:
  build_cli: ^2.2.1
  build_runner: ^2.4.4
  custom_lint: ^0.3.4
  dart_pre_commit: ^5.1.0
  dart_test_tools: ^5.1.0
  freezed: ^2.3.3
  http: ^0.13.6
  json_serializable: ^6.6.2
  mocktail: ^0.3.0
  test: ^1.24.2
  tuple: ^2.0.1

dart_pre_commit:
  flutter-compat: false
