name: dynssh
description: A small server utility to dynamically update the SSH configuration for a remote host with dynamic IPs.
version: 1.0.7
publish_to: none

environment:
  sdk: ^3.2.0

platforms:
  linux:
  macos:

executables:
  dynssh:

dependencies:
  args: ^2.4.2
  build_cli_annotations: ^2.1.0
  collection: ^1.18.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  meta: ^1.12.0
  posix: ^6.0.1
  riverpod: ^2.5.0
  synchronized: ^3.1.0+1

dev_dependencies:
  build_cli: ^2.2.3
  build_runner: ^2.4.8
  custom_lint: ^0.6.0
  dart_pre_commit: ^5.2.1
  dart_test_tools: ^5.6.1
  freezed: ^2.4.7
  http: ^1.2.0
  json_serializable: ^6.7.1
  mocktail: ^1.0.3
  test: ^1.25.2

dart_pre_commit:
  flutter-compat: false

cider:
  link_template:
    tag: https://github.com/Skycoder42/dynssh/releases/tag/v%tag%
    diff: https://github.com/Skycoder42/dynssh/compare/v%from%...v%to%
