name: Continuous integration

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  ci:
    uses: ./.github/workflows/ci_base.yaml
  cd:
    name: CD
    needs:
      - ci
    uses: Skycoder42/dart_test_tools/.github/workflows/compile.yml@main
    with:
      buildRunner: true

  docker:
    needs:
      - cd
    if: needs.cd.outputs.releaseCreated == 'true'
    uses: ./.github/workflows/docker_base.yaml
    with:
      dockerImageTags: |
        latest
        ${{ needs.cd.outputs.version }}
    secrets:
      dockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
