name: Continuous integration

on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      platforms: '["linux", "windows", "macos"]'
      buildRunner: true
      extendedAnalyzerArgs: --linter test-import # Do not run the lib-export linter
      coverageExclude: >-
        "**/*.freezed.dart"
        "**/*.g.dart"
  cd:
    name: CD
    needs:
      - ci
    uses: Skycoder42/dart_test_tools/.github/workflows/compile.yml@main
    with:
      platforms: '["linux", "windows", "macos"]'
      buildRunner: true
