on:
  workflow_call:
jobs:
  ci:
    name: CI
    uses: Skycoder42/dart_test_tools/.github/workflows/dart.yml@main
    with:
      buildRunner: true
      extendedAnalyzerArgs: --linter test-import # Do not run the lib-export linter
      unitTestPaths: -P unit
      coverageExclude: >-
        "**/*.freezed.dart"
        "**/*.g.dart"
      integrationTestPaths: -P integration
      integrationTestSetup: >-
        {
          "linux": "./tool/integration-test-setup.sh",
          "macos": "./tool/integration-test-setup.sh"
        }
