name: Weekly - Docker image update

on:
  workflow_dispatch:
  schedule:
    - cron: "25 5 * * 4"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - id: version
        name: Get latest released version
        run: |
          set -eo pipefail
          version=$(yq '.version' pubspec.yaml)
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'docker_update.yaml',
              ref: 'refs/tags/v${{ steps.version.outputs.version }}',
              inputs: {
                version: ${{ steps.version.outputs.version }}
              },
            })
