on:
  workflow_call:
    inputs:
      version:
        type: string
        required: true
      latestOnly:
        type: boolean
        required: true
    secrets:
      dockerHubUsername:
        required: true
      dockerHubToken:
        required: true
jobs:
  docker:
    name: Docker
    uses: Skycoder42/dart_test_tools/.github/workflows/docker.yml@main
    with:
      imageName: skycoder42/dynssh
      version: ${{ inputs.version }}
      latestOnly: ${{ inputs.latestOnly }}
      dockerPlatforms: linux/amd64,linux/arm64,linux/arm/v7
    secrets:
      dockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
