name: Docker image update

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
        description: The version to be published. Should match the branch

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci_base.yaml

  docker:
    name: Docker
    needs:
      - ci
      - get_version
    uses: ./.github/workflows/docker_base.yaml
    with:
      version: ${{ inputs.version }}
      latestOnly: true
    secrets:
      dockerHubUsername: ${{ secrets.DOCKERHUB_USERNAME }}
      dockerHubToken: ${{ secrets.DOCKERHUB_TOKEN }}
